name: responsive_vs_adaptive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-97.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  material_symbols_icons: ^4.2858.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
